services:
  users-db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: users_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5433:5432'
    volumes:
      - users-db-data:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -d users_db']
      interval: 5s
      timeout: 5s
      retries: 5

  notes-db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: notes_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5434:5432'
    volumes:
      - notes-db-data:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -d notes_db']
      interval: 5s
      timeout: 5s
      retries: 5

  nats:
    image: nats:2-alpine
    ports:
      - '4222:4222'
      - '8222:8222'
    command: '--http_port 8222 --user nats --pass natspassword'
    networks:
      - app-network

volumes:
  users-db-data:
  notes-db-data:

networks:
  app-network:
    driver: bridge
