apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
  namespace: stopphish
type: Opaque
stringData:
  USERS_DB_USER: postgres
  USERS_DB_PASSWORD: postgres
  NOTES_DB_USER: postgres
  NOTES_DB_PASSWORD: postgres
  JWT_SECRET: your_secret_here
  NATS_USER: nats
  NATS_PASS: natspassword
